common:
    lidar_topic: "/xianfeng/lidar"
    imu_topic: "/xianfeng/imu"
    point_filter_num: 1
    time_sync_en: false
    gravity_acc: [0.0, 0.0, 9.8]

lidar_parameter:
    lidar_type: 2                # Velodyne-style organized PointCloud2
    N_SCANS: 16
    Horizon_SCANS: 900
    ang_res_x: 0.4
    ang_res_y: 2.0
    ang_bottom: 15.1
    ground_scan_id: 7
    SCAN_RATE: 3
    time_unit: 0
    blind: 2
    fov_degree: 180
    det_range: 100.0

imu_parameter:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.01
    b_gyr_cov: 0.01
    time_diff_enable: true
    time_diff: 0.117
    add_gravity_from_orientation: true
    estimate_gravity_from_imu: false

extrinsic_parameter:
    extrinsic_enable: false
    extrinsic_t: [0.0, 0.0, 0.0]
    extrinsic_R: [1, 0, 0,
                  0, 1, 0,
                  0, 0, 1]

odometry_options:
    voxel_size: 0.5
    sample_voxel_size: 1.5
    max_distance: 100.0
    max_num_points_in_voxel: 20
    init_num_frames: 20
    min_distance_points: 0.15
    distance_error_threshold: 100.0
    motion_compensation: CONSTANT_VELOCITY
    initialization: INIT_IMU

icp_options:
    size_voxel_map: 1.0
    num_iters_icp: 5
    min_number_neighbors: 20
    voxel_neighborhood: 1
    max_number_neighbors: 20
    max_dist_to_plane_ct_icp: 0.3
    threshold_orientation_norm: 0.1
    threshold_translation_norm: 0.01
    debug_print: false
    num_closest_neighbors: 1
    min_num_residuals: 200
    max_num_residuals: 600
